version: '3.7'
services:
  dev:
    image: privileges_dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      cache_from:
      - privileges_dev
      - quay.io/nyulibraries/privileges:dev-latest
      - quay.io/nyulibraries/privileges:dev-$BRANCH_NO_SLASH
    ports:
      - "3000:3000"
    environment:
      SOLR_URL: http://solr:8983/solr/development-core
    env_file:
      - test.env
    volumes:
      # - ./:/app/
      # - ./app/:/app/app
      # - ./lib/:/app/lib
      # - ./config:/app/config
      - bundle_cache:/bundle
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - setup_dbs
      - memcached

  test:
    image: privileges_dev
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      cache_from:
      - privileges_dev
      - quay.io/nyulibraries/privileges:dev-latest
      - quay.io/nyulibraries/privileges:dev-$BRANCH_NO_SLASH
    volumes:
      # - .:/app
      - bundle_cache:/bundle
    environment:
      RAILS_ENV: test
      SOLR_URL: http://solr:8983/solr/test-core
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake"]
    depends_on:
      - setup_test_dbs

  setup_dbs:
    image: privileges_dev
    volumes:
      - bundle_cache:/bundle
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    depends_on:
      - solr
      - db

  setup_test_dbs:
    image: privileges_dev
    volumes:
      - bundle_cache:/bundle
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    depends_on:
      - solr
      - db


  # WORKING WITH SQL DATA DUMPS LOCALLY:
  # 1. Dump
  # docker run library/mysql:5.6.22 mysqldump --user={username} -p --host={web.hostdomain.com} {database_name} > privileges_dev.sql
  # 2. Seed
  # docker-compose exec -T db mysql -uroot --host=db privileges < privileges_dev.sql
  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    image: privileges_solr
    build:
      context: ./solr
      dockerfile: Dockerfile
    expose:
      - "8983"

  memcached:
    image: memcached:alpine
    expose:
    - "11211"

  # Use below settings for testing nginx/unicorn locally
  web:
    image: quay.io/nyulibraries/nginx:1.15.8-0
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9292:9292"
    depends_on:
      - unicorn

  unicorn:
    image: privileges
    build:
      context: .
      cache_from:
      - privileges
      - quay.io/nyulibraries/privileges:latest
      - quay.io/nyulibraries/privileges:$BRANCH_NO_SLASH
    command: ["./script/start.sh", "production"]
    expose:
    - "5000"
    environment:
      UNICORN_PORT: 5000
      RAILS_LOG_LEVEL: debug
      SOLR_URL: http://solr:8983/solr/development-core
      RAILS_SERVE_STATIC_FILES: enabled
    env_file:
      - test.env
    depends_on:
      - setup_dbs
      - memcached

volumes:
  bundle_cache:
