version: '3.2'
services:

  dev:
    tty: true
    stdin_open: true
    image: privileges_dev
    build:
      context: .
      cache_from:
      - privileges_dev
      - quay.io/nyulibraries/privileges
      - quay.io/nyulibraries/privileges:$BRANCH_NO_SLASH
    ports:
      - "3000:3000"
    environment:
      SOLR_URL: http://solr:8983/solr/development-core
      MEMCACHED_URL: cache:11211
    env_file:
      - test.env
    volumes:
      # - ./:/app/
      # - ./app/:/app/app
      # - ./lib/:/app/lib
      # - ./config:/app/config
      - bundle_cache:/bundle
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - setup_dbs
      - cache

  test:
    image: privileges_dev
    build:
      context: .
      cache_from:
      - privileges_dev
      - quay.io/nyulibraries/privileges
      - quay.io/nyulibraries/privileges:$BRANCH_NO_SLASH
    stdin_open: true
    tty: true
    volumes:
      # - .:/app
      - bundle_cache:/bundle
    environment:
      RAILS_ENV: test
      SOLR_URL: http://solr:8983/solr/test-core
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "--", "rake"]
    depends_on:
      - setup_test_dbs

  setup_dbs:
    image: privileges_dev
    build:
      context: .
      cache_from:
      - privileges_dev
      - quay.io/nyulibraries/privileges
      - quay.io/nyulibraries/privileges:$BRANCH_NO_SLASH
    volumes:
      - bundle_cache:/bundle
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    # healthcheck:
    #   test: ["CMD", "mysqlshow -uroot|grep privileges"]
    #   timeout: 20s
    #   retries: 10
    depends_on:
      - solr
      - db

  setup_test_dbs:
    image: privileges_dev
    build:
      context: .
      cache_from:
      - privileges_dev
      - quay.io/nyulibraries/privileges
      - quay.io/nyulibraries/privileges:$BRANCH_NO_SLASH
    volumes:
      - bundle_cache:/bundle
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["/tmp/wait-for-it.sh", "db:3306", "solr:8983", "--", "rake", "db:setup"]
    # healthcheck:
    #   test: ["CMD", "mysqlshow -uroot|grep privileges_test"]
    #   timeout: 20s
    #   retries: 10
    depends_on:
      - solr
      - db

  db:
    image: library/mysql:5.6.22
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    # volumes:
    # - ./privileges_dev.sql:/app/privileges_dev.sql

    # WORKING WITH SQL DATA DUMPS LOCALLY:
    # docker run library/mysql:5.6.22 mysqldump --user={username} -p --host={web.hostdomain.com} privileges_dev > privileges_dev.sql
    # docker cp {CONTAINER_ID}:/app/privileges_dev.sql privileges_dev.sql
    # docker-compose up dev
    # docker-compose exec db mysql -uroot -p --host=db privileges < /app/privileges_dev.sql
    # docker-compose exec dev rails db:seed

  solr:
    image: privileges_solr
    build:
      context: ./solr
      dockerfile: Dockerfile
    expose:
      - "8983"
    ports:
      - "8983:8983"

  cache:
    image: memcached:alpine
    expose:
    - "11211"

volumes:
  bundle_cache:
