version: '3.7'

x-build-default: &build_default
  image: privileges
  build:
    context: .
    cache_from:
      - privileges
      - quay.io/nyulibraries/privileges:$BRANCH_NO_SLASH
      - quay.io/nyulibraries/privileges:latest
    args:
      AQUA_MICROSCANNER_TOKEN: ${AQUA_MICROSCANNER_TOKEN}

x-build-test: &build_test
  image: privileges_test
  build:
    context: .
    dockerfile: Dockerfile.test
    cache_from:
      - privileges_test
      - quay.io/nyulibraries/privileges_test:$BRANCH_NO_SLASH
      - quay.io/nyulibraries/privileges_test:latest

services:
  dev:
    <<: *build_test
    ports:
      - "3000:3000"
    environment:
      SOLR_URL: http://solr:8983/solr/development-core
    env_file:
      - test.env
    command: ["./wait-for.sh", "db:3306", "--", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    depends_on:
      - setup_dbs
      - memcached

  test:
    <<: *build_test
    environment:
      RAILS_ENV: test
      SOLR_URL: http://solr:8983/solr/test-core
      CI:
      CODECLIMATE_REPO_TOKEN:
      COVERALLS_REPO_TOKEN:
    env_file:
      - test.env
    command: ["./wait-for.sh", "db:3306", "--", "bundle", "exec", "rake"]
    depends_on:
      - setup_test_dbs

  setup_dbs:
    <<: *build_test
    env_file:
      - test.env
    command: ["./wait-for.sh", "db:3306", "--", "./wait-for.sh", "solr:8983", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - solr
      - db

  setup_test_dbs:
    <<: *build_test
    environment:
      RAILS_ENV: test
    env_file:
      - test.env
    command: ["./wait-for.sh", "db:3306", "--", "./wait-for.sh", "solr:8983", "--", "bundle", "exec", "rake", "db:setup"]
    depends_on:
      - solr
      - db


  # WORKING WITH SQL DATA DUMPS LOCALLY:
  # 1. Dump
  # docker run library/mysql:5.6.22 mysqldump --user={username} -p --host={web.hostdomain.com} {database_name} > privileges_dev.sql
  # 2. Seed
  # docker-compose exec -T db mysql -uroot --host=db privileges < privileges_dev.sql
  db:
    image: library/mysql:5.6.22
    ports:
      - 3306:3306
      #expose:
      #  - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    image: privileges_solr
    build:
      context: ./solr
      dockerfile: Dockerfile
    ports:
      - 8983:8983
        #expose:
        #  - "8983"

  memcached:
    image: memcached:alpine
    expose:
      - "11211"

  # Use below settings for testing nginx/unicorn locally
  web:
    image: quay.io/nyulibraries/nginx:1.15.8-0
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9292:9292"
    depends_on:
      - unicorn

  unicorn:
    <<: *build_default
    command: ["./script/start.sh", "production"]
    expose:
      - "5000"
    environment:
      UNICORN_PORT: 5000
      RAILS_LOG_LEVEL: debug
      SOLR_URL: http://solr:8983/solr/development-core
      RAILS_SERVE_STATIC_FILES: enabled
    env_file:
      - test.env
    depends_on:
      - setup_dbs
      - memcached

  deploy:
    <<: *dev-env
    tty: true
    stdin_open: true
    command: "mkdir -p ~/.ssh && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts && \
              bundle exec cap $DEPLOY_ENV deploy:setup && bundle exec cap $DEPLOY_ENV deploy"
    user: root
    environment:
      SSH_AUTH_SOCK: '/ssh-agent'
      GIT_COMMIT: "$GIT_COMMIT"
    volumes:
      - "${HOST_SSH_AUTH_SOCK}:/ssh-agent"
