development: &development
  host: <%= Settings.databases.host %>
  database: <%= Settings.databases.database %>
  username: <%= Settings.databases.username %>
  password: <%= Settings.databases.password %>
  adapter: mysql2
  encoding: utf8

test: 
  <<: *development
  
staging:
  <<: *development
  
qa:
  <<: *development

production:  
  <<: *development
  

  