# Default public settings

global:
  local_creation_prefix: "nyu_ag_noaleph_"
  
databases: 
  password: 
  username: root
  database: nyu_privileges_guide_test
  host: localhost

capistrano:
  server: 
  user: 
  path: 
  scm_username: 

sunspot:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

newrelic:
  api_key: 
  app_name: 'Privileges Guide'

login:
  default_admins: []
  pds_url: "https://login.library.nyu.edu"
  calling_system: "primo"
  
secret_token: 